# Generated by Django 2.2.5 on 2021-01-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210105_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bed',
            new_name='beds',
        ),
    ]
